import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Layout from "~/components/layout/Layout";

import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        < title >MeepleMatch</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/3d-meeple-svgrepo-com.svg" />
      </Head >
      <Layout>
        <main className=" flex min-h-screen flex-col items-center justify-center bg-blue-400">

          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              <img className="h-20 mr-5 inline" src="/3d-meeple-svgrepo-com.svg" /><span className="text-black">Meeple</span>Match
            </h1>
            <h2 className="font-bold text-2xl"><span className="text-white">Guaranteed Fun </span><span className="text-black">&#40;For Everyone&#41;</span></h2>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white transition-all hover:-translate-y-2 hover:bg-white/20"
                href="/Library"
              // target="_blank"
              >
                <h3 className="text-2xl font-bold">Track your board games</h3>
                <div className="text-lg">
                  Catalog your Board Game collection with ease.
                </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white transition-all hover:-translate-y-2 hover:bg-white/20"
                href="/gameMatcher"
              // target="_blank"
              >
                <h3 className="text-2xl font-bold">Find the perfect game</h3>
                <div className="text-lg">
                  Input your players, difficulty, and time. We'll choose the perfect game.
                </div>
              </Link>
            </div>
            <div className="flex flex-col items-center gap-2">
              <p className="text-2xl text-white">
                {/* {hello.data ? hello.data.greeting : "Loading tRPC query..."} */}
              </p>
              <AuthShowcase />
              {/* /*The auth showcase lets the user login by using the Discord provider of NextAuth. */}
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();
  //use the useSession function from nextAuth
  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    //fetch the secretMessage from the example api router defined in trpc. 
    //this is the API -- instead of using REST syntax, we can access the backend using the useQuery function of trpc.
    undefined, // no input. this function doesn't require anything -- it simply returns the value. 
    { enabled: sessionData?.user !== undefined }
    //an object where enabled is set to a boolean that tells us if a user is present by accessing the session data. no session data, then it is set to false. 
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button>
        {sessionData ? "Sign out" : "Sign in to get started!"}
      </button>
    </div >

  );
}
